require("telescope").setup({})
local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", function()
  builtin.find_files({ hidden = true })
end, { desc = "Find files" })
vim.keymap.set("n", "<leader>fg", function()
  builtin.live_grep({ additional_args = { "--hidden" } })
end, { desc = "Live grep" })
-- Escape hatch: also include gitignored files (node_modules, build output, …)
vim.keymap.set("n", "<leader>fh", function()
  builtin.find_files({ hidden = true, no_ignore = true })
end, { desc = "Find files (all, no ignore)" })
vim.keymap.set("n", "<leader>fH", function()
  builtin.live_grep({ additional_args = { "--hidden", "--no-ignore" } })
end, { desc = "Live grep (all, no ignore)" })
vim.keymap.set("n", "<leader>fb", builtin.buffers,    { desc = "Buffers" })
vim.keymap.set("n", "<leader>ft", builtin.help_tags,  { desc = "Help tags" })
vim.keymap.set("n", "<leader>fk", builtin.keymaps,    { desc = "Keymaps" })

